### ISSUE TITLE
I find some error for this image?

### ISSUE THREAD

**Issue by c1a1o1** [quanhua92/human-pose-estimation-opencv#3]
https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1544691320461&di=3a212dc919f9e02968e26704a2040ea2&imgtype=0&src=http%3A%2F%2Fimgsrc.baidu.com%2Fimgad%2Fpic%2Fitem%2F7acb0a46f21fbe0909572e3d60600c338744ad8a.jpg

**Comment by c1a1o1** [comment]
![4](https://user-images.githubusercontent.com/7991905/49919159-97572400-fee0-11e8-8d5a-36e728ebb917.jpg)

**Comment by quanhua92** [comment]
@c1a1o1 this is the problem of the model. I suggest that  you should try the original [OpenPose from OpenCV](https://github.com/opencv/opencv/blob/master/samples/dnn/openpose.py) or the [original OpenPose repo](https://github.com/CMU-Perceptual-Computing-Lab/openpose).
This repo only shows how to use the MobileNet OpenPose model provided by [ildoonet/tf-pose-estimation](https://github.com/ildoonet/tf-pose-estimation/tree/master/models/graph/mobilenet_thin), instead of `Caffe Model` from CMU OpenPose.
